theme: jekyll-theme-slate
url: https://mbasedcyber.github.io/
title: Merritt Based Cyber Learning Project
description: Training with Character
<img src="{{site.url}}/images/mb.png" style="display: block; margin: auto;" />
